export const list = [
  {
    id: 1,
    title: "Apartment in  Maten al Sahel",
    location: "Maten al Sahel, Tartus",
    price: "500,000",
    description:
      "Maten al Sahel apartment! 1 bedroom, large living area with amazing mountain & Mediterranean Sea views. Perfect for relaxation, enjoy the beauty from your balcony.",
    arabicDescription:
      "شقة ساحرة في متن الساحل! غرفة نوم واحدة، ومساحة معيشة واسعة مطلة على مناظر خلابة للجبال والبحر الأبيض المتوسط. مثالية للاسترخاء، استمتع بالجمال من شرفتك الخاصة.",
    image: [
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent4.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent5.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent2.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent3.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent6.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent7.jpeg",
      "/images/matenalsahelchalet/matenalsahel-tartus-syria-chalet-apartment-forrent-airbnb-rentals-amazingviewforrent1.jpeg",
    ],
    cardDescription:
      "Escape to your modern Maten al Sahel apartment. Breathtaking mountain and Mediterranean views await!",
    hostedBy: "george",
    guests: 3,
    rooms: 2,
    bathrooms: 2,
    addedamenities: 5,
    Features: {
      wifi: true,
      mountainView: true,
      nearbyAttractions: true,
      uniqeExperiance: true,
      pets: true,
      tv: true,
      kitchen: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d8795.360544460298!2d35.91725387102254!3d34.997133898042414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523d8836ed081ef%3A0x960cd850b5ad39c2!2z2YXYqtmGINin2YTYs9in2K3ZhNiMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2snl!4v1713916457689!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 2,
    title: "Traditional House in Al Sawda",
    location: "Al Sawda, Tartus",
    price: "850,000",
    description:
      "Traditional 3-bedroom house with big garden & salon. Relax in a historic village near Tartus, known for its black stone architecture. (Interior photos available upon request)",
    arabicDescription:
      "منزل تراثي ساحر مكون من ثلاث غرف نوم مع حديقة كبيرة وصالة. استرخ في قرية تاريخية بالقرب من طرطوس، تشتهر بعمارتها الحجرية السوداء. (الصور الداخلية متاحة عند الطلب)",
    image: [
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals5.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals9.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals8.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals13.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals4.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals7.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals2.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals3.jpg",
      "/images/alsawdahouse/alsawda-tartus-syria-home-house-villaforrent-airbnb-rentals12.jpg",
    ],
    cardDescription:
      "Black Stone Escape! Traditional 3BR house near Tartus. Large garden, salon. Immerse yourself in history!",
    hostedBy: "Andreh",
    guests: 6,
    rooms: 5,
    bathrooms: 2,
    addedamenities: 6,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      nearbyAttractions: true,
      airConditioning: true,
      kitchen: true,
      parking: true,
      garden: true,
      tv: true,
      grill: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6537.964120701257!2d35.94920860538175!3d34.982114081776665!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523d8589e47b899%3A0x564287ea8ef1ca6e!2z2KfZhNiz2YjYr9in2Iwg2LPZiNix2YrYpw!5e0!3m2!1sar!2snl!4v1713922577016!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 3,
    title: "Luxurious Villa in Madaya",
    location: "Madaya, Damascus",
    price: "3300,000",
    description:
      "Spacious Luxury in Madaya:  This 6-bedroom villa in Madaya provides ample space for families and friends. Enjoy a private pool, sauna, billiards room, and large gardens with games for a fun-filled Syrian vacation.",
    arabicDescription:
      " فيلا فخمة في كروم مضايا توفر هذه الفيلا المكونة من 6 غرف نوم مساحة واسعة للعائلات والأصدقاء. استمتع بمسبح خاص وساونا وغرفة بلياردو وحدائق كبيرة مع ألعاب لقضاء إجازة سورية مليئة بالمرح.",
    image: [
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals10.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals3.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals9.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals8.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals6.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals5.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals12.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals11.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals4.jpeg",
      "/images/damascusmadaiavilla/madaya-damascus-syria-villa-villaforrent-airbnb-rentals13.jpeg",
    ],
    cardDescription:
      "Syrian escape: Luxurious villa. Family & friends. Splash in the pool, unwind in the sauna. Create memories that linger.",
    hostedBy: "Ziad",
    guests: 10,
    rooms: 9,
    bathrooms: 3,
    addedamenities: 10,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      mountainView: true,
      airConditioning: true,
      kitchen: true,
      parking: true,
      garden: true,
      pool: true,
      grill: true,
      tv: true,
      billiards: true,
      pets: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26557.556146765914!2d36.117141893506954!3d33.69097334860235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518c57aa1a8ab8d%3A0xa6173f968baf610e!2z2YXYttin2YrYp9iMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2s!4v1713964763455!5m2!1sar!2s",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 4,
    title: "Chalet in Golden Sands",
    location: "Golden Sands, Tartus",
    price: "1200,000",
    description:
      "In Golden Sands, Tartus, this cozy chalet with two bedrooms and a welcoming living room invites you to enjoy the summer vibe. Close to the beach, it's your perfect retreat for relaxation and fun in Tartus.",
    arabicDescription:
      " في الرمال الذهبية، طرطوس، هذه الشاليه المريحة المكونة من غرفتي نوم وغرفة معيشة جذابة تدعوك للاستمتاع بأجواء الصيف. قريبة من الشاطئ، إنها ملاذك المثالي للاسترخاء والمتعة في طرطوس. ",
    image: [
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-1.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-2.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-8.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-5.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-4.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-3.jpeg",
      "/images/chaletalremal/goldensands-golden-sands-tartus-syria-chalet-forrent-airbnb-rentals-7.jpeg",
    ],
    cardDescription:
      "Golden Sands retreat! 2 bedrooms, comfy living room. Beachfront bliss - relax & enjoy Tartus!",
    hostedBy: "Talal",
    guests: 5,
    rooms: 4,
    bathrooms: 2,
    addedamenities: 4,
    Features: {
      wifi: true,
      beachAccess: true,
      airConditioning: true,
      pets: true,
      kitchen: true,
      washer: true,
      tv: true,
      grill: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6534.7922379688425!2d35.902722905375605!3d35.021818977457144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152162141f9e31ab%3A0xf5b447615b1cc9b8!2z2KfZhNix2YXYp9mEINin2YTYsNmH2KjZitip!5e0!3m2!1sar!2snl!4v1713963572896!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 5,
    title: "Duplex Apartment in Shahin Resort",
    location: "Shahin Resort, Tartus",
    price: "1600,000",
    description:
      "Shahin Escape! Relax in this spacious duplex apartment (2 salons, 3 bedrooms) at Shahin Resort, Tartus. Unwind by the stunning beach or enjoy cafes nearby. Perfect for your Tartus getaway!",
    arabicDescription:
      "استرخ في شقتك الفسيحة المكونة من دورين (صالونان، 3 غرف نوم) في منتجع شاهين. اقضِ وقتًا ممتعًا على شاطئ منتجع شاهين الخلاب أو استمتع بالمقاهي القريبة. مثالية لقضاء عطلتك في طرطوس! ",
    image: [
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals8.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals5.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals6.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals4.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals7.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals1.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals2.jpeg",
      "/images/shahinvilla/shahinresort-tartus-syria-apartment-chalet-chaletforrent-airbnb-rentals3.jpeg",
    ],
    cardDescription:
      "Shahin Escape! Duplex apt. (2 salons, 3 bedrooms) near stunning beach & cafes. Your Tartus retreat!",
    hostedBy: "Ibrahem",
    guests: 6,
    rooms: 5,
    bathrooms: 2,
    addedamenities: 5,
    Features: {
      wifi: true,
      airConditioning: true,
      beachAccess: true,
      kitchen: true,
      grill: true,
      parking: true,
      tv: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3276.066053841208!2d35.9226689!3d34.80428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523d57958dcaea7%3A0x8b459242bd494ce!2z2YXZhtiq2KzYuSDYtNin2YfZitmG!5e0!3m2!1sar!2snl!4v1713961939465!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 6,
    title: "Villa in Madaya",
    location: "Madaya, Damascus",
    price: "2700,000",
    description:
      "Magical Madaya awaits! This 4-bedroom villa boasts indoor & outdoor pools for year-round fun. Relax in multiple living areas or unwind in the vast garden with a terrace overlooking the mountains. Perfect for families & friends, this Syrian escape promises unforgettable memories.",
    arabicDescription:
      " فيلا فخمة بأربع غرف نوم، تجمع بين متعة المسابح الداخلية والخارجية على مدار السنة. استرخ في صالات المعيشة المتعددة أو تأمل منظر الجبال الخلاب من حديقة واسعة مع تراس. ملاذ سوري مثالي للعائلات والأصدقاء، يضمن ذكريات لا تُمحى. ",
    image: [
      "/images/damascusmadaiavilla2/damascusmadaiavilla22.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla24.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla27.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla212.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla210.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla26.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla29.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla211.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla25.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla23.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla28.jpg",
      "/images/damascusmadaiavilla2/damascusmadaiavilla21.jpg",
    ],
    cardDescription:
      "4BR villa, indoor/outdoor pools, vast garden & terrace. Perfect family & friend escape.",
    hostedBy: "Ziad",
    guests: 8,
    rooms: 7,
    bathrooms: 3,
    addedamenities: 8,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      mountainView: true,
      airConditioning: true,
      kitchen: true,
      parking: true,
      garden: true,
      pool: true,
      grill: true,
      tv: true,
      billiards: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26557.556146765914!2d36.117141893506954!3d33.69097334860235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518c57aa1a8ab8d%3A0xa6173f968baf610e!2z2YXYttin2YrYp9iMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2s!4v1713964763455!5m2!1sar!2s",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 7,
    title: "Chalet in Golden Sands",
    location: "Golden Sands, Tartus",
    price: "1050,000",
    description:
      "Golden Sands Charm! Relax in this 1-salon, 2-bedroom chalet with a balcony view of mountains & Golden Sands resort. Steps from the beach - your Tartus escape!",
    arabicDescription:
      "استرخ في شاليه ساحر بغرفة معيشة واسعة وغرفتي نوم وشرفة مطلة على الجبال ومنتجع الرمال الذهبية. على بعد خطوات قليلة من الشاطئ - ملاذك في طرطوس!",
    image: [
      "/images/goldensandstartuschalet/goldensandstartuschalet2.jpeg",
      "/images/goldensandstartuschalet/goldensandstartuschalet1.jpeg",
      "/images/goldensandstartuschalet/goldensandstartuschalet5.jpeg",
      "/images/goldensandstartuschalet/goldensandstartuschalet3.jpeg",
      "/images/goldensandstartuschalet/goldensandstartuschalet6.jpeg",
    ],
    cardDescription:
      "Mountain & Sea Views! Golden Sands chalet (1 salon, 2 bedrooms). Balcony paradise - relax near the beach!",
    hostedBy: "Luna",
    guests: 4,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 4,
    Features: {
      wifi: true,
      beachAccess: true,
      mountainView: true,
      airConditioning: true,
      kitchen: true,
      refrigerator: true,
      washer: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6534.7922379688425!2d35.902722905375605!3d35.021818977457144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152162141f9e31ab%3A0xf5b447615b1cc9b8!2z2KfZhNix2YXYp9mEINin2YTYsNmH2KjZitip!5e0!3m2!1sar!2snl!4v1713963572896!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 8,
    title: "Cabin in Tartus",
    location: "Coming Soon!",
    price: "--,--",
    description:
      "(Coming Soon) This cozy 2-bedroom cabin boasts stunning waterfall & mountain views. Breathe fresh air, listen to nature & unwind. Perfect for couples or small groups. Stay tuned for details!",
    arabicDescription:
      "  (قريباً) يتميز هذا الكوخ الجميل المكون من غرفتين بإطلالات خلابة على الشلال والجبال. تنفس الهواء الجبلي النقي واستمع إلى الطبيعة واسترخ. مثالي للأزواج أو المجموعات الصغيرة. ترقبوا التفاصيل!",
    image: [
      "/images/cabinintartus/cabin-tartus-lattakia-syria-cabinforrent-airbnb-rentals5.jpg",
      "/images/cabinintartus/cabin-tartus-lattakia-syria-cabinforrent-airbnb-rentals6.jpg",
      "/images/cabinintartus/cabin-tartus-lattakia-syria-cabinforrent-airbnb-rentals2.jpg",
      "/images/cabinintartus/cabin-tartus-lattakia-syria-cabinforrent-airbnb-rentals4.jpg",
      "/images/cabinintartus/cabin-tartus-lattakia-syria-cabinforrent-airbnb-rentals1.jpg",
    ],
    cardDescription:
      "Escape to Tartus! (Coming Soon) Cozy cabin with waterfall view. Perfect for couples or friends. ",
    hostedBy: "Rami",
    guests: 3,
    rooms: 2,
    bathrooms: 1,
    addedamenities: 4,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      mountainView: true,
      nearbyAttractions: true,
      airConditioning: true,
      pets: true,
      garden: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d67058.63778897094!2d36.19555158974769!3d35.082116125461766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523e7baa8e84633%3A0x45635685baa0adbb!2z2KfZhNiz2YXZitit2YrZgtipIC0gc3VtYXloaXFhaA!5e0!3m2!1sar!2snl!4v1713993280012!5m2!1sar!2snl",
    rules: {
      checkIn: "Coming Soon!",
      checkOut: "Coming Soon!",
    },
  },
  {
    id: 9,
    title: "Beachfront Apartment in Golden Sands",
    location: "Golden Sands, Tartus",
    price: "1400,000",
    description:
      "This 2-bedroom apartment offers stunning views, a spacious living area, and direct access to Golden Sands beach in Tartus. Perfect for a relaxing getaway!",
    arabicDescription:
      "توفر هذه الشقة المكونة من غرفتي نوم إطلالات خلابة ومنطقة معيشة واسعة وإمكانية الوصول المباشر إلى شاطئ الرمال الذهبية في طرطوس. مثالية لقضاء عطلة مريحة!",
    image: [
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals4.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals8.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals1.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals7.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals9.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals2.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals6.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals5.jpg",
      "/images/beachfrontapartment/golden-sands-tartus-syria-beachfront-apartment-rentals3.jpg",
    ],
    cardDescription: "Golden Sands Getaway: Balcony Bliss & Beach Steps Away!",
    hostedBy: "Jamil",
    guests: 4,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 7,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      beachAccess: true,
      airConditioning: true,
      pets: true,
      kitchen: true,
      tv: true,
      refrigerator: true,
      grill: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6534.7922379688425!2d35.902722905375605!3d35.021818977457144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152162141f9e31ab%3A0xf5b447615b1cc9b8!2z2KfZhNix2YXYp9mEINin2YTYsNmH2KjZitip!5e0!3m2!1sar!2snl!4v1713963572896!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 10,
    title: "Villa in Madaya",
    location: "Madaya, Damascus",
    price: "1500,000",
    description:
      "Make memories in this 6BR Madaya villa! Featuring an outdoor pool, billiards, ping pong & a vast garden, it's perfect for family & friends to relax & reconnect.",
    arabicDescription:
      " اصنع ذكريات لا تنسى في فيلا مضايا المكونة من 6 غرف نوم! تتميز بمسبح خارجي وبلياردو وتنس طاولة وحديقة واسعة ، وهي مثالية للعائلات والأصدقاء للاسترخاء وإعادة التواصل.",
    image: [
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury1.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury8.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury3.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury4.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury7.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury5.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury6.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury9.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury10.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury12.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury13.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury14.jpg",
      "/images/damascusmadaiavilla3/madaya-damascus-syria-villa-farmhouse-rentals-villajoury15.jpg",
    ],
    cardDescription:
      "Make memories in this Madaya villa! Pool, games & garden for fun",
    hostedBy: "Samer",
    guests: 10,
    rooms: 8,
    bathrooms: 3,
    addedamenities: 6,
    Features: {
      wifi: true,
      mountainView: true,
      airConditioning: true,
      kitchen: true,
      garden: true,
      parking: true,
      pool: true,
      billiards: true,
      tv: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26557.556146765914!2d36.117141893506954!3d33.69097334860235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518c57aa1a8ab8d%3A0xa6173f968baf610e!2z2YXYttin2YrYp9iMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2s!4v1713964763455!5m2!1sar!2s",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 11,
    title: "Traditional House in Slinfah",
    location: "Slinfah, Lattakia",
    price: "680,000",
    description:
      "Experience a traditional 2BR stone house with breathtaking mountain views, balcony & garden. Immerse yourself in the village vibe.",
    arabicDescription:
      "استمتع بتجربة منزل حجري تقليدي يضم غرفتي نوم مع مناظر خلابة للجبال، بالإضافة إلى شرفة وحديقة. انغمس في أجواء القرية.",
    image: [
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals2.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals1.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals4.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals3.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals6.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals7.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals5.jpeg",
      "/images/houseinslinfeh/slinfah-lattakia-syria-house-homeforrent-airbnb-shortrent-rentals8.jpeg",
    ],
    cardDescription:
      "Slinfah Escape! Traditional Stone House with Mountain Views",
    hostedBy: "Mazen",
    guests: 5,
    rooms: 4,
    bathrooms: 2,
    addedamenities: 4,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      mountainView: true,
      nearbyAttractions: true,
      pets: true,
      kitchen: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12976.819441037691!2d36.191344438532006!3d35.5980129096015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1524142e99ec320d%3A0x43694fc591a5346d!2z2LXZhNmG2YHZh9iMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2snl!4v1714211626575!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 12,
    title: "Villa in Madaya",
    location: "Madaya, Damascus",
    price: "1650,000",
    description:
      "This 5-bedroom Madaya villa offers a stylish escape. Featuring a large pool, billiards room, vast garden with games, multiple living areas, and a stunning mountain view terrace, it's perfect for families & friends.",
    arabicDescription:
      " توفر لك هذه الفيلا الأنيقة المكونة من 5 غرف نوم ملاذاً عصرياً في مضايا. استمتع بمسبح كبير وغرفة بلياردو وحديقة واسعة مع ألعاب وصالات معيشة متعددة وتراس يطل على جبال مضايا الخلابة. مثالية للعائلات والأصدقاء.",
    image: [
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals5.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals6.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals2.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals3.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals7.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals4.jpeg",
      "/images/madayaalnourvilla/madaya-damascus-syria-villa-farm-farmhouse-rentals1.jpeg",
    ],
    cardDescription:
      "Relax in this 5BR Madaya villa with pool, billiards & vast garden. Perfect escape! ",
    hostedBy: "Samer",
    guests: 8,
    rooms: 7,
    bathrooms: 3,
    addedamenities: 5,
    Features: {
      wifi: true,
      mountainView: true,
      airConditioning: true,
      kitchen: true,
      parking: true,
      garden: true,
      pool: true,
      billiards: true,
      tv: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26557.556146765914!2d36.117141893506954!3d33.69097334860235!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518c57aa1a8ab8d%3A0xa6173f968baf610e!2z2YXYttin2YrYp9iMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2s!4v1713964763455!5m2!1sar!2s",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 13,
    title: "Beachfront Apartment in Shahin Resort",
    location: "Shahin Resort, Tartus",
    price: "1250,000",
    description:
      "This 2-bedroom apartment boasts a balcony with stunning sea views & direct access to Shahin Resort beach in Tartus. Relax by the Sea!",
    arabicDescription:
      "تحتوي هذه الشقة المكونة من غرفتي نوم على شرفة تتمتع بإطلالات خلابة على البحر وإمكانية الوصول المباشر إلى شاطئ منتجع شاهين في طرطوس. استرخ بجانب البحر!",
    image: [
      "/images/shahintopchalet/shahinresort-tartus-syria-apartment-chalet-rentals5.jpeg",
      "/images/shahintopchalet/shahinresort-tartus-syria-apartment-chalet-rentals4.jpeg",
      "/images/shahintopchalet/shahinresort-tartus-syria-apartment-chalet-rentals2.jpeg",
      "/images/shahintopchalet/shahinresort-tartus-syria-apartment-chalet-rentals1.jpeg",
      "/images/shahintopchalet/shahinresort-tartus-syria-apartment-chalet-rentals3.jpeg",
    ],
    cardDescription:
      "Relax by the Sea! Shahin Beachfront Apartment with Balcony",
    hostedBy: "Kareem",
    guests: 4,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 7,
    Features: {
      uniqeExperiance: true,
      wifi: true,
      beachAccess: true,
      airConditioning: true,
      pets: true,
      tv: true,
      kitchen: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3276.066053841208!2d35.9226689!3d34.80428!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523d50ebf6f8bc5%3A0x694cff1e3ca93d35!2z2YXZhtiq2KzYuSDZiNmF2LPYqNitINi02KfZh9mK2YYg2LfYsdi32YjYsw!5e0!3m2!1sar!2snl!4v1714202601309!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 14,
    title: "Chalet in Mashta al Hilu",
    location: "Mashta al Hilu, Tartus",
    price: "700,000",
    description:
      "Mountain Views & Village Charm! This 2BR chalet in Mashta al-Hilu boasts a balcony with breathtaking vistas. Relax, unwind, and reconnect with nature!",
    arabicDescription:
      "إطلالات على الجبل وسحر القرية! يحتوي هذا الشاليه المكون من غرفتي نوم في مشتى الحلو على شرفة ذات مناظر خلابة. استمتع بالاسترخاء والراحة وإعادة الاتصال بالطبيعة!",
    image: [
      "/images/chaletinmashta/mashtaalhilu-tartus-syria-chalet-apartment-airbnb-rental1.jpeg",
      "/images/chaletinmashta/mashtaalhilu-tartus-syria-chalet-apartment-airbnb-rental5.jpeg",
      "/images/chaletinmashta/mashtaalhilu-tartus-syria-chalet-apartment-airbnb-rental2.jpeg",
      "/images/chaletinmashta/mashtaalhilu-tartus-syria-chalet-apartment-airbnb-rental3.jpeg",
      "/images/chaletinmashta/mashtaalhilu-tartus-syria-chalet-apartment-airbnb-rental4.jpeg",
    ],
    cardDescription:
      "Breathtaking Mountains & Village Charm! 2BR Chalet with Breathtaking Mashta Views ",
    hostedBy: "Michael",
    guests: 4,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 5,
    Features: {
      wifi: true,
      mountainView: true,
      nearbyAttractions: true,
      airConditioning: true,
      pets: true,
      tv: true,
      kitchen: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13092.887648375852!2d36.26380918897431!3d34.87577346956025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523c79067722e3d%3A0x854b1c3729ff025e!2z2YXYtNiq2Ykg2KfZhNit2YTZiNiMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2snl!4v1714206651991!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 15,
    title: "Apartment in Golden Sands",
    location: "Golden Sands, Tartus",
    price: "650,000",
    description:
      "This clean & comfy 1BR apartment near Golden Sands beach offers the essentials for a relaxing getaway.",
    arabicDescription:
      "هذه الشقة النظيفة والمريحة بغرفة نوم واحدة بالقرب من شاطئ الرمال الذهبية توفر كل ما تحتاجه لإجازة مريحة.",
    image: [
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals1.jpg",
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals7.jpg",
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals4.jpg",
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals6.jpg",
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals5.jpg",
      "/images/chaletingoldensandsjamil/goldensands-tartus-syria-holiday-beach-chalet-apartment-airbnb-rentals3.jpg",
    ],
    cardDescription: "Golden Sands Escape: Clean & Cozy (Near Beach!)",
    hostedBy: "Nader",
    guests: 3,
    rooms: 2,
    bathrooms: 1,
    addedamenities: 4,
    Features: {
      wifi: true,
      beachAccess: true,
      airConditioning: true,
      pets: true,
      kitchen: true,
      refrigerator: true,
      washer: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6534.7922379688425!2d35.902722905375605!3d35.021818977457144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152162141f9e31ab%3A0xf5b447615b1cc9b8!2z2KfZhNix2YXYp9mEINin2YTYsNmH2KjZitip!5e0!3m2!1sar!2snl!4v1713963572896!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 16,
    title: "Chalet in Mashta al Hilu",
    location: "Mashta al Hilu, Tartus",
    price: "450,000",
    description:
      "This 2BR chalet in Mashta al-Hilu offers a private balcony with breathtaking views. Immerse yourself in the charm of this mountain village.",
    arabicDescription:
      "يوفّر هذا الشاليه بغرفتي نوم في مشتى الحلو شرفة خاصة تطل على مناظر خلّابة. اغمر نفسك في سحر هذه القرية الجبلية.",
    image: [
      "/images/mashtaalhiluchalet2/mashta-al-hilu-tartus-homs-syria-chalet-apartment-rentals2.jpeg",
      "/images/mashtaalhiluchalet2/mashta-al-hilu-tartus-homs-syria-chalet-apartment-rentals4.jpeg",
      "/images/mashtaalhiluchalet2/mashta-al-hilu-tartus-homs-syria-chalet-apartment-rentals3.jpeg",
      "/images/mashtaalhiluchalet2/mashta-al-hilu-tartus-homs-syria-chalet-apartment-rentals1.jpeg",
      "/images/mashtaalhiluchalet2/mashta-al-hilu-tartus-homs-syria-chalet-apartment-rentals5.jpeg",
    ],
    cardDescription:
      "Mountain Views from Your Balcony! Cozy 2BR Chalet in Mashta al-Hilu",
    hostedBy: "Nour",
    guests: 4,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 4,
    Features: {
      wifi: true,
      mountainView: true,
      nearbyAttractions: true,
      airConditioning: true,
      pets: true,
      tv: true,
      kitchen: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13092.887648375852!2d36.26380918897431!3d34.87577346956025!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1523c79067722e3d%3A0x854b1c3729ff025e!2z2YXYtNiq2Ykg2KfZhNit2YTZiNiMINiz2YjYsdmK2Kc!5e0!3m2!1sar!2snl!4v1714206651991!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
  {
    id: 17,
    title: "Apartment in Golden Sands",
    location: "Golden Sands, Tartus",
    price: "850,000",
    description:
      "This 2-bedroom beachfront apartment offers a private balcony with stunning views of Golden Sands beach in Tartus. Relax by the sea & unwind in comfort.",
    arabicDescription:
      "تقدم هذه الشقة ذات غرفتي نوم على الشاطئ شرفة خاصة تطل على مناظر خلابة لشاطئ الرمال الذهبية في طرطوس. استرخِ عند البحر واستمتع بالراحة.",
    image: [
      "/images/remal/alremalalzahabiahtartuschalet1.jpeg",
      "/images/remal/alremalalzahabiahtartuschalet5.jpeg",
      "/images/remal/alremalalzahabiahtartuschalet6.jpeg",
      "/images/remal/alremalalzahabiahtartuschalet3.jpeg",
      "/images/remal/alremalalzahabiahtartuschalet4.jpeg",
      "/images/remal/alremalalzahabiahtartuschalet2.jpeg",
    ],
    cardDescription:
      "Tartus Escape: Beachfront Bliss with Balcony (2 Bedrooms)",
    hostedBy: "Ahmad",
    guests: 5,
    rooms: 3,
    bathrooms: 2,
    addedamenities: 6,
    Features: {
      wifi: true,
      beachAccess: true,
      airConditioning: true,
      pets: true,
      kitchen: true,
      tv: true,
      refrigerator: true,
    },
    mapId:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6534.7922379688425!2d35.902722905375605!3d35.021818977457144!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x152162141f9e31ab%3A0xf5b447615b1cc9b8!2z2KfZhNix2YXYp9mEINin2YTYsNmH2KjZitip!5e0!3m2!1sar!2snl!4v1713963572896!5m2!1sar!2snl",
    rules: {
      checkIn: "anytime",
      checkOut: "11:00 AM",
    },
  },
];
