export const activities = [
  {
    id: 1,
    title: "Camping on the Beach",
    location: "Armenian Bay, Lattakia",
    date: "Thursday, June 27, 2024",
    level: "Easy",
    headline: "Campfire Stories & Starlight Skies: A Weekend Getaway",
    description:
      "Join us on Thursday, June 27, for a two-night camping adventure on the most beautiful and pristine beaches of our coast. Start with an extended boat trip from Al-Basit Harbor, passing Basit and Badrousia beaches to a secluded bay. Enjoy unique rock formations, social campfires, swimming in clear waters, and a 2 km hike to Samra Village to enjoy the mountains and get supplies. Experience a magical camping night at the crescent-shaped Armenian Bay.",
    arabicDescription:
      "انضموا إلينا يوم الخميس ٢٧ حزيران في مغامرة تخييم لمدة ليلتين على أجمل وأصفى شواطئ ساحلنا. نبدأ برحلة بحرية من ميناء البسيط مروراً بشواطئ البسيط والبدروسية وصولاً إلى خليج معزول. استمتعوا بتشكيلات صخرية فريدة، سهرة جماعية حول النار، السباحة في المياه النقية، ومسير 2 كم إلى قرية السمرا للاستمتاع بالجبال والتزود بالمؤونة. تجربة تخييم ساحرة تحت النجوم في خليج الأرمن الهلالي.",
    host: "Nature Friends",
    price: "from 250,000",
    image: "/activities/campingbybeach.jpeg",
    features: [
      "Camping",
      "Beach",
      "Campfire",
      "Hikking",
      "Views",
      "Social",
      "Wildlife",
      "Bird watching",
    ],
    startingPoint: "lattakia, damascus",
    startingTime: "6 AM from damascus",
  },
  {
    id: 2,
    title: "Zipline and Skybike",
    location: "Al Qadmus, Tartus",
    date: "Coming Soon!",
    level: "Moderate",
    headline: "Experience Al Qadmus from Above!",
    description:
      "Get ready to zip and fly in Al Qadmus! We're bringing Zipline & Skybike adventures your way. Stay tuned for details!",
    arabicDescription:
      "استعدوا للانطلاق والتحليق في القدموس! جلبنا لكم مغامرات الزيب لاين و سكاي بايك. ترقبوا التفاصيل!",
    host: "Al Atlal Zipline",
    price: "--,--",
    image: "/activities/skybike.jpeg",
    features: [
      "Zipline",
      "Skybike",
      "Mountain",
      "Views",
      "Forest",
      "Wildlife",
      "Adventure",
    ],
    startingPoint: "Coming Soon!",
    startingTime: "Coming Soon!",
  },
  {
    id: 3,
    title: "Slunfeh Adventure Camp",
    location: "Slunfeh, Lattakia",
    date: "Expired",
    level: "Easy",
    headline:
      "A Unique Experience to Explore History and Nature in the Heart of the Forest",
    description:
      "Join us for a three-day, two-night camp in Slunfeh's magical forests from June 18-20. Enjoy guided tours of ancient caves, visit the Monastery of the Virgin Mary and the Cave of Jesus Christ, learn fire-starting and rappelling skills, and explore with hands-on climbing demonstrations. Experience cozy bonfires and the serene beauty of the forest.",
    arabicDescription:
      "انضم إلينا في مخيم لمدة ثلاثة أيام وليلتين في غابات صلنفة الساحرة من 18 إلى 20 يونيو. استمتع بجولات تعريفية على الكهوف الأثرية، وزيارة دير السيدة العذراء ومغارة السيد يسوع المسيح، وتعلم مهارات إشعال النار والإنزال الجبلي، واستكشف الموقع بتجارب عملية لتسلق الأشجار. استمتع بالسهرة حول نار المخيم وجمال الطبيعة الهادئ في الغابة.",
    host: "Syrian Association for Mountain Activities",
    price: "from 175,000",
    image: "/activities/slinfehcamping.jpeg",
    features: [
      "Camping",
      "Walking",
      "Campfire",
      "Views",
      "Wildlife",
      "Bird watching",
      "Forest",
      "Social",
      "History",
    ],
    startingPoint: "damascus, lattakia, homs",
    startingTime: "9 AM",
  },
  {
    id: 4,
    title: "Wadi al-Kahf Adventure Trip",
    location: "Al Qadmus, Tartus",
    date: "On Demand",
    level: "Moderate",
    headline:
      "Explore Syria's Wadi al-Kahf: Hike, swim & discover hidden beauty!",
    description:
      "The Northern Cave Valley in Tartous Governorate is an ideal destination for nature and adventure lovers, as it provides a wonderful path that combines swimming in natural rock pools, rock climbing, exploring a historical castle, and enjoying stunning panoramic views, The trail begins at the Hamam Waasil River and heads north along a valley rich in captivating details, where you will encounter distinctive rock pools.",
    arabicDescription:
      "يُعدّ وادي الكهف الشمالي في محافظة طرطوس وجهة مثالية لمحبي الطبيعة والمغامرة، حيث يوفر مسارًا رائعًا يجمع بين السباحة في أحواض صخرية طبيعية، وتسلق الصخور، واستكشاف قلعة تاريخية، والاستمتاع بإطلالات بانورامية خلابة, يبدأ المسار من نهر حمام واصل، ويتجه شمالًا على طول وادي غني بالتفاصيل الساحرة، حيث ستصادفون أحواض السباحة الصخرية المميزة.",
    host: "Nature Friends",
    price: "--,--",
    image: "/activities/cave2.jpg",
    features: [
      "Trekking",
      "Walking",
      "Historical Experience",
      "River",
      "Views",
      "Social",
      "Wildlife",
      "Bird watching",
    ],
    startingPoint: "inquiry required",
    startingTime: "inquiry required",
  },
  {
    id: 5,
    title: "Camping on the beach",
    location: "Om-AlTuyoor, Lattakia",
    date: "Expired",
    level: "Easy",
    headline: "Beach Camping at Om AlTuyoor",
    description:
      "Experience the charm of Om AlTuyoor Beach with a camping adventure from Thursday, June 6, to Friday, June 7. Marvel at the captivating scenery where the sea meets the mountains for a truly enchanting getaway. Don't miss this chance to create unforgettable memories under the starlit sky.",
    arabicDescription:
      "عش تجربة ساحل أم الطيور الساحرة في مغامرة تخييم رائعة تمتد من الخميس 6 يونيو إلى الجمعة 7 يونيو. انظر إلى المناظر الطبيعية الآسرة حيث يلتقي البحر بالجبال لقضاء إجازة ساحرة حقًا. لا تفوت هذه الفرصة لتكوين ذكريات لا تُنسى تحت سماء مليئة بالنجوم.",
    host: "Nature Friends",
    price: "from 100,000",
    image: "/activities/wadiqandil.jpeg",
    features: [
      "Camping",
      "Walking",
      "Beach",
      "Campfire",
      "Views",
      "Fishing",
      "Bird watching",
    ],
    startingPoint: "lattakia",
    startingTime: "3 PM",
  },
  {
    id: 6,
    title: "Qalat Al Kahf Camp & Adventure",
    location: "Al Qadmus, Tartus",
    date: "Expired",
    level: "Easy",
    headline:
      "Dive into Nature's Wonders - Unforgettable Camping Trip at Qalat Al Kahf (May 23-25)",
    description:
      "Are you ready for an extraordinary adventure to Qalat Al Kahf? Join us from May 23rd to 25th for a unique camping trip with an amphibious twist! We'll explore the beauty of Mawla Hasan Forest, witness the majesty of the castle's waterfalls, visit the historic Qalat Al Kahf itself, and take a dip in the refreshing natural streams. Nature enthusiasts and adventure seekers will love this trip. We'll have a variety of activities including camping, learning to manage campfires, scenic hikes, and even an optional advanced amphibious experience! Don't miss this chance to discover the hidden wonders of Qalat Al Kahf and create unforgettable memories in the heart of nature!",
    arabicDescription:
      "انضم إلينا في رحلة استثنائية إلى قلعة الكهف (من 23 إلى 25 أيار)! حيث سنقيم مخيمًا ونخوض تجربة برمائية فريدة من نوعها. سنستكشف غابة المولى حسن، ونشاهد شلالات القلعة، ونزور قلعة الكهف، ونسبح في الجداول العذبة. رحلة مثالية لمحبي الطبيعة والمغامرة، مع أنشطة متنوعة مثل إقامة المخيم، وإدارة نار المخيم، والمشي لمسافات طويلة، وتجربة توغل برمائي متقدم (اختياري). لا تفوت فرصة اكتشاف قلعة الكهف وخوض مغامرة لا تُنسى في قلب الطبيعة الساحرة!",
    host: "Syrian Association for Mountain Activities",
    price: "from 150,000",
    image: "/activities/cc9.jpg",
    features: [
      "Camping",
      "Walking",
      "River",
      "Views",
      "Forest",
      "Campfire",
      "Trekking",
      "Social",
      "Wildlife",
      "Bird watching",
    ],
    startingPoint: "damascus, homs, banias",
    startingTime: "inquiry required",
  },
  {
    id: 7,
    title: "Farzla River Trekking Adventure",
    location: "Paradise Valley, Lattakia",
    date: "Expired",
    level: "Moderate",
    headline:
      "Farzla River Adventure: Hike, Waterfalls, & Natural Pools (May 10th)",
    description:
      "Join us for an unforgettable aquatic adventure next Friday, May 10th, in the stunning Farzla River!  We'll start by diving into a refreshing natural rock pool, perfect for warming up before exploring the majestic Waterfall.  Hike through lush forests teeming with life,  and navigate the fascinating Rocky Trenches filled with unique rock formations, including the awe-inspiring Hanging Rock .The hike is a moderate 4km, perfect for those who love spending time in nature and enjoy a refreshing swim. Don't worry if you're not a pro swimmer, there's just a short, easy submerged section (around 8 meters).",
    arabicDescription:
      "تعالوا معنا في رحلة مائية لا تُنسى الجمعة القادمة، 10 مايو، في نهر فرزلا الخلاب! سنبدأ بالغطس في بركة صخرية طبيعية منعشة، مثالية للاستعداد لاستكشاف شلال الحجاب المهيب. ثم نتجه في مسير عبر غابات يانعة مليئة بالحياة، ونشق طريقنا عبر منطقة الخنادق الصخرية المذهلة التي تزخر بتشكيلات صخرية فريدة، بما في ذلك صخرة معلقة تخطف الأنفاس. تبلغ مسافة الرحلة 4 كيلومترات وهي سهلة إلى حد ما، ومثالية لعشاق الطبيعة والسباحة المنعشة. لا تقلق إذا لم تكن سباحًا محترفًا، فهناك قسم مغمور قصير وسهل (حوالي 8 أمتار)   .",
    host: "Nature Friends",
    price: "90,000",
    image: "/activities/trekking.jpeg",
    features: [
      "Walking",
      "River",
      "Views",
      "Swimming",
      "Trekking",
      "Social",
      "Bird watching",
      "Wildlife",
    ],
    startingPoint: "lattakia",
    startingTime: "9 AM from lattakia",
  },
  {
    id: 8,
    title: "Camping Near the Basqin River",
    location: "Basqin River, Lattakia",
    date: "Expired",
    level: "Easy",
    headline: "Create Lasting Memories: Basqin River Camping Adventure",
    description:
      "Calling all nature lovers!  Escape the ordinary and unwind by the beautiful Basqin River (May 16th-18th). Imagine waking up to the gentle sounds of flowing water and lush greenery all around. Relax under the shade of trees, take a dip in the crystal-clear river, and gather around a crackling campfire to enjoy delicious meals. Feeling adventurous? Join us for a fun jungle trek and discover hidden wonders! Here's what makes your escape special: Effortless Camping: Our campsite is conveniently close to the bus stop (with baggage transfer!), so you can relax without lugging heavy bags. Comfy & Easy: Bring your snacks and drinks (don't forget your swimsuit!), and choose between pitching your own tent or renting one from us. Sleeping bags are also available. Unforgettable Experiences: Relax by the river, explore the jungle, and enjoy activities planned just for you. Escape the everyday and create lasting memories!",
    arabicDescription:
      "عشاق الطبيعة، تعالوا إلى ملاذكم الهادئ بجانب نهر بسقين الرائع (من 16 إلى 18 أيار)! تخيلوا الاستيقاظ على أصوات المياه المتدفقة والطبيعة الخضراء المحيطة بكم. استرخوا تحت ظلال الأشجار، خذوا غطسة منعشة في المياه الصافية، وتجمعوا حول نار المخيم المتوهجة لتستمتعوا بوجبات لذيذة. هل تشعرون بالحماس؟ انضموا إلينا في رحلة ممتعة في الغابة واكتشفوا عجائبها المخفية! ما يميز رحلتكم: تخييم مريح: موقع التخييم قريب جدًا من موقف الحافلات, سهولة وراحة: احضروا وجباتكم الخفيفة والمشروبات (لا تنسوا ملابس السباحة!) واختاروا بين نصب خيمتكم الخاصة أو استئجار واحدة منا. تتوفر أيضًا أكياس النوم للإيجار. تجارب لا تُنسى: استريحوا بجانب النهر، واستكشفوا الغابة، واستمتعوا بالأنشطة المخطط لها خصيصًا لكم. اهربوا من الروتين واصنعوا ذكريات لا تُنسى!",
    host: "Nature Friends",
    price: "from 120,000",
    image: "/activities/campingbyriver.jpeg",
    features: [
      "Camping",
      "Walking",
      "River",
      "Views",
      "Forest",
      "Wildlife",
      "Bird watching",
    ],
    startingPoint: "lattakia, damascus",
    startingTime: "7:15 AM from damascus",
  },
  {
    id: 9,
    title: "Trip to Bakramah, Jabal al-Malek & Wadi al-Muluk",
    location: "Lattakia",
    date: "Expired",
    level: "Moderate",
    headline:
      "Waterfalls, Mountains & Views - Bekrama, Wadi Al Muluk & Jabal Al Malik Adventure!",
    description:
      "Awesome Friday trip this May 17th! We'll chill by a Bekrama waterfall, explore Wadi Al Muluk, then conquer the views from Jabal Al Malik's peak!  Delicious food & fun for everyone!",
    arabicDescription:
      " انطلق معنا برحلة جمعة مميزة إلى بكراما ووادي الملوك وجبل الملك يوم 17 مايو!  الاسترخاء بجانب شلال رائع، ومغامرة استكشافية في وادي الملوك، وصولا إلى مشهد بانورامي يخطف الأنفاس من قمة جبل الملك، طعام شهي وفعاليات ترفيه للجميع!",
    host: "Nature Friends",
    price: "from 125,000",
    image: "/activities/king.jpeg",
    features: [
      "Walking",
      "River",
      "Views",
      "Swimming",
      "Mountain",
      "Social",
      "Bird watching",
      "Wildlife",
    ],
    startingPoint: "lattakia, tartus",
    startingTime: "9 AM from lattakia",
  },
];
